### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#166]
Hi @cinaaaa,
there are a couple of resources which are not found. Could you have a look onto them and try to fix them? 
![grafik](https://user-images.githubusercontent.com/49870195/210513914-fc368317-77e1-434a-86b9-20b59f04fa4d.png)
(Screenshot from Netlify)

Thanks!

**Comment by cinaaaa** [comment]
@UJehle  I just Fixed the robots, these URLs are not valid and even not exist in the project and mostly requested by crawlers and search engines or sometimes spammer to crawl and fetch the data or maybe for some people who looking for security valunabrities.
So no worries about it and no need to make them a valide URL.
But the website was with WordPress in the past?!

**Comment by UJehle** [comment]
Hi @cinaaaa, thanks. I just had a look at Netlify and it still shows that the robots.txt could not be found. 
![grafik](https://user-images.githubusercontent.com/49870195/214035093-b7da745d-89de-4ccc-9e9e-694879d43a3d.png)
Okay, thanks. Then we can just ignore these missing files, right?

**Comment by cinaaaa** [comment]
@UJehle I opened the merge requests to fix the bugs but they're not merged yet and until then we have the fixed errors remain unfixed, and yeah we should ignore these unknown URLs and missing resources.

**Comment by UJehle** [comment]
Sorry, I have somehow overseen the PR :D I just merged it.
